### ISSUE TITLE
Kundera 2.8 blows my Cassandra app

### ISSUE THREAD

**Issue by pires** [Impetus/kundera#433]
I have an app that was working with 2.8-SNAPSHOT as of 53f8840 but no longer works with 2.8 release.

Here's the error output:

<pre>
08:39:38.183 [main] DEBUG c.i.k.m.processor.IndexProcessor - Processing @Entity pt.lighthouselabs.sherlock.model.AuditRecord for Indexes.
08:39:38.188 [main] INFO  c.i.k.c.ClientMetadataBuilder - Loading client factory for persistence unit SherlockPU
08:39:38.188 [main] INFO  c.i.kundera.client.ClientResolver - Initializing client factory for: SherlockPU
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/Analyzer
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at com.impetus.kundera.client.ClientResolver.instantiateClientFactory(ClientResolver.java:90)
    at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:56)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:39)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:349)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:113)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:65)
    at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:205)
    at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:119)
</pre>

I found a workaround by adding the following to my `pom.xml`:

``` xml
<dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-core</artifactId>
      <version>4.5.0</version>
</dependency>
```

**Comment by mevivs** [comment]
Fixed and releasing with 2.8.1
