### ISSUE TITLE
Persistence Problem

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#628]
Getting below exception while creating EntityManagerFactory when using Kundera vesion > 2.11. I have used the previous versions of Kundera and there was no problem. Changed POM to point to new versions and getting this exception. I have again changed to previous version and it worked fine. 

java.lang.NoClassDefFoundError: javax/persistence/Persistence
    com.leuven.lmaas.dmmiddleware.damiddleware.KunderaEntityManagerFactory.createEntityManager(KunderaEntityManagerFactory.java:26)
    com.leuven.lmaas.dmmiddleware.damiddleware.DataAccessService.<init>(DataAccessService.java:16)
    com.leuven.lmaas.dmmiddleware.services.DataManagementService.<init>(DataManagementService.java:25)
    com.leuven.lmaas.client.controller.LogDataStorage.init(LogDataStorage.java:47)
    javax.servlet.GenericServlet.init(GenericServlet.java:160)
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:744)

**Comment by chhavigangwal** [comment]
Can you share further details ?
Also please try upgrading it to latest version (2.13) to check if the issue still persists ?

Chhavi

**Comment by ansarrafique** [comment]
I have verified it with the version 2.13. I am getting the same exception. If I use it with the previous of Kundera, I don't see problem any more and it works for me. Any clue ?

**Comment by chhavigangwal** [comment]
Which version of Java are you using ?
From 2.11.1 onward Kundera requires JDK 7 and works with Cassandra 2.x versions, best compatible with 2.0.4.

Chhavi

**Comment by ansarrafique** [comment]
I am using Java 7 and Cassandra 2.0.9. I am getting java.lang.NoClassDefFoundError: javax/persistence/Persistence exception. However, the same code works fine if I point out to previous versions of Kundera

```
    <dependency>
        <groupId>com.impetus.kundera.client</groupId>
        <artifactId>kundera-cassandra-ds-driver</artifactId>
        <version>2.11.1</version>
    </dependency>
    <dependency>
        <groupId>com.impetus.kundera.client</groupId>
        <artifactId>kundera-mongo</artifactId>
        <version>2.12-1.x</version>
    </dependency>
```

**Comment by ansarrafique** [comment]
I have created a simple project and it works fine with Kundera 2.13, but if I create a web project then I am getting an exception. I think the problem is with the persistence.xml file and Kundera is not able to find it in web application. 

java.lang.ClassNotFoundException: javax.persistence.Persistence
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at com.leuven.lmaas.dmmiddleware.damiddleware.KunderaEntityManagerFactory.createTenantEntityManager(KunderaEntityManagerFactory.java:39)
    at com.leuven.lmaas.dmmiddleware.damiddleware.DataAccessService.store(DataAccessService.java:36)
    at com.leuven.lmaas.dmmiddleware.services.DataManagementService.storeObject(DataManagementService.java:46)
    at com.leuven.lmaas.client.controller.LogDataStorage.doGet(LogDataStorage.java:62)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

Where should I place persistence.xml file ? With the previous Kundera versions, I have placed it in src -> META-INF and it worked fine, but not working with 2.13. Any clue.

**Comment by ansarrafique** [comment]
Problem solved.

**Comment by chhavigangwal** [comment]
@ansarrafique 

Glad to know your problem got resolved !
Can you please share what was the actual issue as we were looking into it simultaneously ?

Chhavi

**Comment by ansarrafique** [comment]
Thanks Chhavi and I really apologies, I forgot to discuss the solution. I was executing a Java EE code, but Java EE API jar was  missing in tomcat server.
